### ISSUE TITLE
Can't set timers inside simulations

### ISSUE THREAD

**Issue by kenrogers** [gwendall/meteor-template-animations-demo#1]
Hey gwendall, trying out your package this morning and ran into the following error when trying to animate an element on removing it.

![image](https://cloud.githubusercontent.com/assets/7418051/7433198/2e77a114-efec-11e4-8e7d-b5837763e334.png)

Here is my HTML code:

```
<div class="goals-group">
  {{#each goals}}
    <div class="row single-goal-container">
      {{>goalItem}}
    </div>
  {{/each}}
</div>
```

Here is the JS:

```
Template.categoryItem.animations({
    '.single-goal-container': {
        container: '.goals-group',
        in: 'animated fadeIn',
        out: 'animated fadeOut',
        animateInitial: true,
        animateInitialStep: 200
    }
});
```

The animations work fine when inserting a new element, but for some reason throw this error when trying to remove an element.

**Comment by gwendall** [comment]
I just updated the package, the issue should be fixed now. Can you get the update and let me know whether it fixes your pb?

**Comment by kenrogers** [comment]
Yup that did it, thanks!

**Comment by gwendall** [comment]
Great, you're welcome!
